<a href="https://colab.research.google.com/github/ananyadix/final-taskBDCOE/blob/main/Untitled3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [50]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder
from datetime import datetime

In [5]:
df=pd.read_csv("/content/train.csv")

In [6]:
df.head()

,customer_id,Name,age,gender,security_no,region_category,membership_category,joining_date,joined_through_referral,referral_id,...,avg_time_spent,avg_transaction_value,avg_frequency_login_days,points_in_wallet,used_special_discount,offer_application_preference,past_complaint,complaint_status,feedback,churn_risk_score
0,fffe4300490044003600300030003800,Pattie Morrisey,18,F,XW0DQ7H,Village,Platinum Membership,17-08-2017,No,xxxxxxxx,...,300.63,53005.25,17,781.75,Yes,Yes,No,Not Applicable,Products always in Stock,2.0
1,fffe43004900440032003100300035003700,Traci Peery,32,F,5K0N3X1,City,Premium Membership,28-08-2017,?,CID21329,...,306.34,12838.38,10,NaN,Yes,No,Yes,Solved,Quality Customer Care,1.0
2,fffe4300490044003100390032003600,Merideth Mcmeen,44,F,1F2TCL3,Town,No Membership,11-11-2016,Yes,CID12313,...,516.16,21027.00,22,500.69,No,Yes,Yes,Solved in Follow-up,Poor Website,5.0
3,fffe43004900440036003000330031003600,Eufemia Cardwell,37,M,VJGJ33N,City,No Membership,29-10-2016,Yes,CID3793,...,53.27,25239.56,6,567.66,No,Yes,Yes,Unsolved,Poor Website,5.0
4,fffe43004900440031003900350030003600,Meghan Kosak,31,F,SVZXCWB,City,No Membership,12-09-2017,No,xxxxxxxx,...,113.13,24483.66,16,663.06,No,Yes,Yes,Solved,Poor Website,5.0

In [7]:
df.shape

(9018, 25)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9018 entries, 0 to 9017
Data columns (total 25 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   customer_id                   9018 non-null   object
 1   Name                          9018 non-null   object
 2   age                           9018 non-null   int64
 3   gender                        9018 non-null   object
 4   security_no                   9018 non-null   object
 5   region_category               7676 non-null   object
 6   membership_category           9018 non-null   object
 7   joining_date                  9018 non-null   object
 8   joined_through_referral       9018 non-null   object
 9   referral_id                   9018 non-null   object
 10  preferred_offer_types         8950 non-null   object
 11  medium_of_operation           9017 non-null   object
 12  internet_option               9017 non-null   object
 13  last_visit_time               9017 non-null   object
 14  days_since_last_login         9017 non-null   float64
 15  avg_time_spent                9017 non-null   float64
 16  avg_transaction_value         9017 non-null   float64
 17  avg_frequency_login_days      9017 non-null   object
 18  points_in_wallet              8166 non-null   float64
 19  used_special_discount         9017 non-null   object
 20  offer_application_preference  9017 non-null   object
 21  past_complaint                9017 non-null   object
 22  complaint_status              9017 non-null   object
 23  feedback                      9017 non-null   object
 24  churn_risk_score              9017 non-null   float64
dtypes: float64(5), int64(1), object(19)
memory usage: 1.7+ MB

In [9]:
df.isnull().sum()

customer_id                        0
Name                               0
age                                0
gender                             0
security_no                        0
region_category                 1342
membership_category                0
joining_date                       0
joined_through_referral            0
referral_id                        0
preferred_offer_types             68
medium_of_operation                1
internet_option                    1
last_visit_time                    1
days_since_last_login              1
avg_time_spent                     1
avg_transaction_value              1
avg_frequency_login_days           1
points_in_wallet                 852
used_special_discount              1
offer_application_preference       1
past_complaint                     1
complaint_status                   1
feedback                           1
churn_risk_score                   1
dtype: int64

In [10]:
df.region_category.mode()[0]

'Town'

In [11]:
df["region_category"]=df["region_category"].fillna(df["region_category"].mode()[0])

In [12]:
df["preferred_offer_types"]=df["preferred_offer_types"].fillna(df["preferred_offer_types"].mode()[0])

In [13]:
df["points_in_wallet"]=df["points_in_wallet"].fillna(df["points_in_wallet"].mean())

In [14]:
df.isnull().sum()

customer_id                     0
Name                            0
age                             0
gender                          0
security_no                     0
region_category                 0
membership_category             0
joining_date                    0
joined_through_referral         0
referral_id                     0
preferred_offer_types           0
medium_of_operation             1
internet_option                 1
last_visit_time                 1
days_since_last_login           1
avg_time_spent                  1
avg_transaction_value           1
avg_frequency_login_days        1
points_in_wallet                0
used_special_discount           1
offer_application_preference    1
past_complaint                  1
complaint_status                1
feedback                        1
churn_risk_score                1
dtype: int64

In [15]:
df.describe()

,age,days_since_last_login,avg_time_spent,avg_transaction_value,points_in_wallet,churn_risk_score
count,9018.000000,9017.000000,9017.000000,9017.000000,9018.000000,9017.000000
mean,37.198935,-43.630476,249.508716,29084.157305,685.039285,3.473772
std,15.955443,232.289828,402.176691,19440.326610,183.337282,1.420710
min,10.000000,-999.000000,-2093.121606,806.220000,-549.357498,-1.000000
25%,23.000000,8.000000,62.040000,14141.450000,623.745000,3.000000
50%,37.000000,12.000000,165.400000,27114.490000,685.039285,4.000000
75%,51.000000,16.000000,361.280000,40536.050000,756.860000,5.000000
max,64.000000,26.000000,2770.560000,99810.830000,1755.455512,5.000000

In [29]:
df["Gender"]=LabelEncoder().fit_transform(df['gender'])
df.drop(["gender"],axis=1)

,customer_id,Name,age,security_no,region_category,membership_category,joining_date,joined_through_referral,referral_id,preferred_offer_types,...,avg_transaction_value,avg_frequency_login_days,points_in_wallet,used_special_discount,offer_application_preference,past_complaint,complaint_status,feedback,churn_risk_score,Gender
0,fffe4300490044003600300030003800,Pattie Morrisey,18,XW0DQ7H,Village,Platinum Membership,17-08-2017,No,xxxxxxxx,Gift Vouchers/Coupons,...,53005.25,17,781.750000,Yes,Yes,No,Not Applicable,Products always in Stock,2.0,0
1,fffe43004900440032003100300035003700,Traci Peery,32,5K0N3X1,City,Premium Membership,28-08-2017,?,CID21329,Gift Vouchers/Coupons,...,12838.38,10,685.039285,Yes,No,Yes,Solved,Quality Customer Care,1.0,0
2,fffe4300490044003100390032003600,Merideth Mcmeen,44,1F2TCL3,Town,No Membership,11-11-2016,Yes,CID12313,Gift Vouchers/Coupons,...,21027.00,22,500.690000,No,Yes,Yes,Solved in Follow-up,Poor Website,5.0,0
3,fffe43004900440036003000330031003600,Eufemia Cardwell,37,VJGJ33N,City,No Membership,29-10-2016,Yes,CID3793,Gift Vouchers/Coupons,...,25239.56,6,567.660000,No,Yes,Yes,Unsolved,Poor Website,5.0,1
4,fffe43004900440031003900350030003600,Meghan Kosak,31,SVZXCWB,City,No Membership,12-09-2017,No,xxxxxxxx,Credit/Debit Card Offers,...,24483.66,16,663.060000,No,Yes,Yes,Solved,Poor Website,5.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9013,fffe43004900440035003500370033003000,Enid Vanepps,55,59SRC59,Town,Platinum Membership,02-03-2017,No,xxxxxxxx,Without Offers,...,33078.33,28,703.520000,Yes,No,No,Not Applicable,No reason specified,3.0,0
9014,fffe43004900440032003000300038003400,Gay Bittinger,35,UDUBCXQ,City,Silver Membership,09-09-2017,?,CID43690,Gift Vouchers/Coupons,...,49810.10,22,662.100000,No,Yes,Yes,Solved in Follow-up,Poor Customer Service,4.0,0
9015,fffe43004900440033003200330037003800,Lenita Ibarra,51,6VN89MW,Town,Basic Membership,04-05-2015,No,xxxxxxxx,Credit/Debit Card Offers,...,20343.39,14,662.980000,Yes,No,Yes,Unsolved,No reason specified,5.0,0
9016,fffe43004900440031003800350035003500,Danica Modeste,36,09XB2DS,Village,Gold Membership,09-03-2017,No,xxxxxxxx,Gift Vouchers/Coupons,...,2191.75,32.19093588,763.880000,No,Yes,No,Not Applicable,Reasonable Price,1.0,0
9017,fffe43004900440032003400330039003400,Walter Coryell,61,F21CQBN,Town,No Membership,21-01-2016,No,xxxxxxxx,Gift Voucher,...,NaN,NaN,685.039285,NaN,NaN,NaN,NaN,NaN,NaN,0

In [32]:
df=df.drop([9017],axis=0)

In [33]:
df.isnull().sum()

customer_id                     0
Name                            0
age                             0
gender                          0
security_no                     0
region_category                 0
membership_category             0
joining_date                    0
joined_through_referral         0
referral_id                     0
preferred_offer_types           0
medium_of_operation             0
internet_option                 0
last_visit_time                 0
days_since_last_login           0
avg_time_spent                  0
avg_transaction_value           0
avg_frequency_login_days        0
points_in_wallet                0
used_special_discount           0
offer_application_preference    0
past_complaint                  0
complaint_status                0
feedback                        0
churn_risk_score                0
Gender                          0
dtype: int64

In [36]:
df["Region"]=LabelEncoder().fit_transform(df['region_category'])
df["Membership"]=LabelEncoder().fit_transform(df['membership_category'])
df["preference"]=LabelEncoder().fit_transform(df["preferred_offer_types"])
df["reference"]=LabelEncoder().fit_transform(df["joined_through_referral"])
df["medium"]=LabelEncoder().fit_transform(df["medium_of_operation"])
df["internet"]=LabelEncoder().fit_transform(df["internet_option"])
df["discount"]=LabelEncoder().fit_transform(df["used_special_discount"])
df["complaint"]=LabelEncoder().fit_transform(df["past_complaint"])
df["Feedback"]=LabelEncoder().fit_transform(df["feedback"])

In [41]:
train=df.drop(['gender','region_category','membership_category',"preferred_offer_types","joined_through_referral","medium_of_operation","internet_option","used_special_discount","past_complaint","feedback"],axis=1)

In [42]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9017 entries, 0 to 9016
Data columns (total 25 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   customer_id                   9017 non-null   object
 1   Name                          9017 non-null   object
 2   age                           9017 non-null   int64
 3   security_no                   9017 non-null   object
 4   joining_date                  9017 non-null   object
 5   referral_id                   9017 non-null   object
 6   last_visit_time               9017 non-null   object
 7   days_since_last_login         9017 non-null   float64
 8   avg_time_spent                9017 non-null   float64
 9   avg_transaction_value         9017 non-null   float64
 10  avg_frequency_login_days      9017 non-null   object
 11  points_in_wallet              9017 non-null   float64
 12  offer_application_preference  9017 non-null   object
 13  complaint_status              9017 non-null   object
 14  churn_risk_score              9017 non-null   float64
 15  Gender                        9017 non-null   int64
 16  Region                        9017 non-null   int64
 17  Membership                    9017 non-null   int64
 18  preference                    9017 non-null   int64
 19  reference                     9017 non-null   int64
 20  medium                        9017 non-null   int64
 21  internet                      9017 non-null   int64
 22  discount                      9017 non-null   int64
 23  complaint                     9017 non-null   int64
 24  Feedback                      9017 non-null   int64
dtypes: float64(5), int64(11), object(9)
memory usage: 1.7+ MB

In [45]:
train=train.drop(['customer_id','Name','security_no','referral_id','avg_frequency_login_days','offer_application_preference','complaint_status'],axis=1)

In [46]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9017 entries, 0 to 9016
Data columns (total 18 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   age                    9017 non-null   int64
 1   joining_date           9017 non-null   object
 2   last_visit_time        9017 non-null   object
 3   days_since_last_login  9017 non-null   float64
 4   avg_time_spent         9017 non-null   float64
 5   avg_transaction_value  9017 non-null   float64
 6   points_in_wallet       9017 non-null   float64
 7   churn_risk_score       9017 non-null   float64
 8   Gender                 9017 non-null   int64
 9   Region                 9017 non-null   int64
 10  Membership             9017 non-null   int64
 11  preference             9017 non-null   int64
 12  reference              9017 non-null   int64
 13  medium                 9017 non-null   int64
 14  internet               9017 non-null   int64
 15  discount               9017 non-null   int64
 16  complaint              9017 non-null   int64
 17  Feedback               9017 non-null   int64
dtypes: float64(5), int64(11), object(2)
memory usage: 1.2+ MB

In [49]:
train['joining_date'] = pd.to_datetime(train['joining_date'])

<ipython-input-49-32bebe2e42b3>:1: UserWarning: Parsing dates in DD/MM/YYYY format when dayfirst=False (the default) was specified. This may lead to inconsistently parsed dates! Specify a format to ensure consistent parsing.
  train['joining_date'] = pd.to_datetime(train['joining_date'])

In [52]:
train['year']=train['joining_date'].dt.year
train['month']=train['joining_date'].dt.month
train['day']=train['joining_date'].dt.day

In [53]:
train=train.drop(['joining_date'],axis=1)

In [54]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9017 entries, 0 to 9016
Data columns (total 20 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   age                    9017 non-null   int64
 1   last_visit_time        9017 non-null   object
 2   days_since_last_login  9017 non-null   float64
 3   avg_time_spent         9017 non-null   float64
 4   avg_transaction_value  9017 non-null   float64
 5   points_in_wallet       9017 non-null   float64
 6   churn_risk_score       9017 non-null   float64
 7   Gender                 9017 non-null   int64
 8   Region                 9017 non-null   int64
 9   Membership             9017 non-null   int64
 10  preference             9017 non-null   int64
 11  reference              9017 non-null   int64
 12  medium                 9017 non-null   int64
 13  internet               9017 non-null   int64
 14  discount               9017 non-null   int64
 15  complaint              9017 non-null   int64
 16  Feedback               9017 non-null   int64
 17  year                   9017 non-null   int64
 18  month                  9017 non-null   int64
 19  day                    9017 non-null   int64
dtypes: float64(5), int64(14), object(1)
memory usage: 1.4+ MB

In [56]:
train['last_visit_time'] = pd.to_datetime(train['last_visit_time'])

In [65]:
train['hour']=train['last_visit_time'].dt.hour
train['min']=train['last_visit_time'].dt.minute
train['sec']=train['last_visit_time'].dt.second

In [66]:
train=train.drop(['last_visit_time'],axis=1)

In [67]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9017 entries, 0 to 9016
Data columns (total 22 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   age                    9017 non-null   int64
 1   days_since_last_login  9017 non-null   float64
 2   avg_time_spent         9017 non-null   float64
 3   avg_transaction_value  9017 non-null   float64
 4   points_in_wallet       9017 non-null   float64
 5   churn_risk_score       9017 non-null   float64
 6   Gender                 9017 non-null   int64
 7   Region                 9017 non-null   int64
 8   Membership             9017 non-null   int64
 9   preference             9017 non-null   int64
 10  reference              9017 non-null   int64
 11  medium                 9017 non-null   int64
 12  internet               9017 non-null   int64
 13  discount               9017 non-null   int64
 14  complaint              9017 non-null   int64
 15  Feedback               9017 non-null   int64
 16  year                   9017 non-null   int64
 17  month                  9017 non-null   int64
 18  day                    9017 non-null   int64
 19  hour                   9017 non-null   int64
 20  min                    9017 non-null   int64
 21  sec                    9017 non-null   int64
dtypes: float64(5), int64(17)
memory usage: 1.5 MB