<a href="https://colab.research.google.com/github/ananyadix/final-taskBDCOE/blob/main/Untitled3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder
from datetime import datetime

In [2]:
df=pd.read_csv("/content/train.csv")

In [3]:
df.head()

,customer_id,Name,age,gender,security_no,region_category,membership_category,joining_date,joined_through_referral,referral_id,...,avg_time_spent,avg_transaction_value,avg_frequency_login_days,points_in_wallet,used_special_discount,offer_application_preference,past_complaint,complaint_status,feedback,churn_risk_score
0,fffe4300490044003600300030003800,Pattie Morrisey,18,F,XW0DQ7H,Village,Platinum Membership,17-08-2017,No,xxxxxxxx,...,300.63,53005.25,17,781.75,Yes,Yes,No,Not Applicable,Products always in Stock,2.0
1,fffe43004900440032003100300035003700,Traci Peery,32,F,5K0N3X1,City,Premium Membership,28-08-2017,?,CID21329,...,306.34,12838.38,10,NaN,Yes,No,Yes,Solved,Quality Customer Care,1.0
2,fffe4300490044003100390032003600,Merideth Mcmeen,44,F,1F2TCL3,Town,No Membership,11-11-2016,Yes,CID12313,...,516.16,21027.00,22,500.69,No,Yes,Yes,Solved in Follow-up,Poor Website,5.0
3,fffe43004900440036003000330031003600,Eufemia Cardwell,37,M,VJGJ33N,City,No Membership,29-10-2016,Yes,CID3793,...,53.27,25239.56,6,567.66,No,Yes,Yes,Unsolved,Poor Website,5.0
4,fffe43004900440031003900350030003600,Meghan Kosak,31,F,SVZXCWB,City,No Membership,12-09-2017,No,xxxxxxxx,...,113.13,24483.66,16,663.06,No,Yes,Yes,Solved,Poor Website,5.0

In [4]:
df.shape

(9018, 25)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9018 entries, 0 to 9017
Data columns (total 25 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   customer_id                   9018 non-null   object
 1   Name                          9018 non-null   object
 2   age                           9018 non-null   int64
 3   gender                        9018 non-null   object
 4   security_no                   9018 non-null   object
 5   region_category               7676 non-null   object
 6   membership_category           9018 non-null   object
 7   joining_date                  9018 non-null   object
 8   joined_through_referral       9018 non-null   object
 9   referral_id                   9018 non-null   object
 10  preferred_offer_types         8950 non-null   object
 11  medium_of_operation           9017 non-null   object
 12  internet_option               9017 non-null   object
 13  last_visit_time               9017 non-null   object
 14  days_since_last_login         9017 non-null   float64
 15  avg_time_spent                9017 non-null   float64
 16  avg_transaction_value         9017 non-null   float64
 17  avg_frequency_login_days      9017 non-null   object
 18  points_in_wallet              8166 non-null   float64
 19  used_special_discount         9017 non-null   object
 20  offer_application_preference  9017 non-null   object
 21  past_complaint                9017 non-null   object
 22  complaint_status              9017 non-null   object
 23  feedback                      9017 non-null   object
 24  churn_risk_score              9017 non-null   float64
dtypes: float64(5), int64(1), object(19)
memory usage: 1.7+ MB

In [6]:
df.isnull().sum()

customer_id                        0
Name                               0
age                                0
gender                             0
security_no                        0
region_category                 1342
membership_category                0
joining_date                       0
joined_through_referral            0
referral_id                        0
preferred_offer_types             68
medium_of_operation                1
internet_option                    1
last_visit_time                    1
days_since_last_login              1
avg_time_spent                     1
avg_transaction_value              1
avg_frequency_login_days           1
points_in_wallet                 852
used_special_discount              1
offer_application_preference       1
past_complaint                     1
complaint_status                   1
feedback                           1
churn_risk_score                   1
dtype: int64

In [7]:
df.region_category.mode()[0]

'Town'

In [8]:
df["region_category"]=df["region_category"].fillna(df["region_category"].mode()[0])

In [9]:
df["preferred_offer_types"]=df["preferred_offer_types"].fillna(df["preferred_offer_types"].mode()[0])

In [10]:
df["points_in_wallet"]=df["points_in_wallet"].fillna(df["points_in_wallet"].mean())

In [11]:
df.isnull().sum()

customer_id                     0
Name                            0
age                             0
gender                          0
security_no                     0
region_category                 0
membership_category             0
joining_date                    0
joined_through_referral         0
referral_id                     0
preferred_offer_types           0
medium_of_operation             1
internet_option                 1
last_visit_time                 1
days_since_last_login           1
avg_time_spent                  1
avg_transaction_value           1
avg_frequency_login_days        1
points_in_wallet                0
used_special_discount           1
offer_application_preference    1
past_complaint                  1
complaint_status                1
feedback                        1
churn_risk_score                1
dtype: int64

In [12]:
df.describe()

,age,days_since_last_login,avg_time_spent,avg_transaction_value,points_in_wallet,churn_risk_score
count,9018.000000,9017.000000,9017.000000,9017.000000,9018.000000,9017.000000
mean,37.198935,-43.630476,249.508716,29084.157305,685.039285,3.473772
std,15.955443,232.289828,402.176691,19440.326610,183.337282,1.420710
min,10.000000,-999.000000,-2093.121606,806.220000,-549.357498,-1.000000
25%,23.000000,8.000000,62.040000,14141.450000,623.745000,3.000000
50%,37.000000,12.000000,165.400000,27114.490000,685.039285,4.000000
75%,51.000000,16.000000,361.280000,40536.050000,756.860000,5.000000
max,64.000000,26.000000,2770.560000,99810.830000,1755.455512,5.000000

In [13]:
df["Gender"]=LabelEncoder().fit_transform(df['gender'])
df.drop(["gender"],axis=1)

,customer_id,Name,age,security_no,region_category,membership_category,joining_date,joined_through_referral,referral_id,preferred_offer_types,...,avg_transaction_value,avg_frequency_login_days,points_in_wallet,used_special_discount,offer_application_preference,past_complaint,complaint_status,feedback,churn_risk_score,Gender
0,fffe4300490044003600300030003800,Pattie Morrisey,18,XW0DQ7H,Village,Platinum Membership,17-08-2017,No,xxxxxxxx,Gift Vouchers/Coupons,...,53005.25,17,781.750000,Yes,Yes,No,Not Applicable,Products always in Stock,2.0,0
1,fffe43004900440032003100300035003700,Traci Peery,32,5K0N3X1,City,Premium Membership,28-08-2017,?,CID21329,Gift Vouchers/Coupons,...,12838.38,10,685.039285,Yes,No,Yes,Solved,Quality Customer Care,1.0,0
2,fffe4300490044003100390032003600,Merideth Mcmeen,44,1F2TCL3,Town,No Membership,11-11-2016,Yes,CID12313,Gift Vouchers/Coupons,...,21027.00,22,500.690000,No,Yes,Yes,Solved in Follow-up,Poor Website,5.0,0
3,fffe43004900440036003000330031003600,Eufemia Cardwell,37,VJGJ33N,City,No Membership,29-10-2016,Yes,CID3793,Gift Vouchers/Coupons,...,25239.56,6,567.660000,No,Yes,Yes,Unsolved,Poor Website,5.0,1
4,fffe43004900440031003900350030003600,Meghan Kosak,31,SVZXCWB,City,No Membership,12-09-2017,No,xxxxxxxx,Credit/Debit Card Offers,...,24483.66,16,663.060000,No,Yes,Yes,Solved,Poor Website,5.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9013,fffe43004900440035003500370033003000,Enid Vanepps,55,59SRC59,Town,Platinum Membership,02-03-2017,No,xxxxxxxx,Without Offers,...,33078.33,28,703.520000,Yes,No,No,Not Applicable,No reason specified,3.0,0
9014,fffe43004900440032003000300038003400,Gay Bittinger,35,UDUBCXQ,City,Silver Membership,09-09-2017,?,CID43690,Gift Vouchers/Coupons,...,49810.10,22,662.100000,No,Yes,Yes,Solved in Follow-up,Poor Customer Service,4.0,0
9015,fffe43004900440033003200330037003800,Lenita Ibarra,51,6VN89MW,Town,Basic Membership,04-05-2015,No,xxxxxxxx,Credit/Debit Card Offers,...,20343.39,14,662.980000,Yes,No,Yes,Unsolved,No reason specified,5.0,0
9016,fffe43004900440031003800350035003500,Danica Modeste,36,09XB2DS,Village,Gold Membership,09-03-2017,No,xxxxxxxx,Gift Vouchers/Coupons,...,2191.75,32.19093588,763.880000,No,Yes,No,Not Applicable,Reasonable Price,1.0,0
9017,fffe43004900440032003400330039003400,Walter Coryell,61,F21CQBN,Town,No Membership,21-01-2016,No,xxxxxxxx,Gift Voucher,...,NaN,NaN,685.039285,NaN,NaN,NaN,NaN,NaN,NaN,0

In [14]:
df=df.drop([9017],axis=0)

In [15]:
df.isnull().sum()

customer_id                     0
Name                            0
age                             0
gender                          0
security_no                     0
region_category                 0
membership_category             0
joining_date                    0
joined_through_referral         0
referral_id                     0
preferred_offer_types           0
medium_of_operation             0
internet_option                 0
last_visit_time                 0
days_since_last_login           0
avg_time_spent                  0
avg_transaction_value           0
avg_frequency_login_days        0
points_in_wallet                0
used_special_discount           0
offer_application_preference    0
past_complaint                  0
complaint_status                0
feedback                        0
churn_risk_score                0
Gender                          0
dtype: int64

In [16]:
df["Region"]=LabelEncoder().fit_transform(df['region_category'])
df["Membership"]=LabelEncoder().fit_transform(df['membership_category'])
df["preference"]=LabelEncoder().fit_transform(df["preferred_offer_types"])
df["reference"]=LabelEncoder().fit_transform(df["joined_through_referral"])
df["medium"]=LabelEncoder().fit_transform(df["medium_of_operation"])
df["internet"]=LabelEncoder().fit_transform(df["internet_option"])
df["discount"]=LabelEncoder().fit_transform(df["used_special_discount"])
df["complaint"]=LabelEncoder().fit_transform(df["past_complaint"])
df["Feedback"]=LabelEncoder().fit_transform(df["feedback"])

In [17]:
train=df.drop(['gender','region_category','membership_category',"preferred_offer_types","joined_through_referral","medium_of_operation","internet_option","used_special_discount","past_complaint","feedback"],axis=1)

In [18]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9017 entries, 0 to 9016
Data columns (total 25 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   customer_id                   9017 non-null   object
 1   Name                          9017 non-null   object
 2   age                           9017 non-null   int64
 3   security_no                   9017 non-null   object
 4   joining_date                  9017 non-null   object
 5   referral_id                   9017 non-null   object
 6   last_visit_time               9017 non-null   object
 7   days_since_last_login         9017 non-null   float64
 8   avg_time_spent                9017 non-null   float64
 9   avg_transaction_value         9017 non-null   float64
 10  avg_frequency_login_days      9017 non-null   object
 11  points_in_wallet              9017 non-null   float64
 12  offer_application_preference  9017 non-null   object
 13  complaint_status              9017 non-null   object
 14  churn_risk_score              9017 non-null   float64
 15  Gender                        9017 non-null   int64
 16  Region                        9017 non-null   int64
 17  Membership                    9017 non-null   int64
 18  preference                    9017 non-null   int64
 19  reference                     9017 non-null   int64
 20  medium                        9017 non-null   int64
 21  internet                      9017 non-null   int64
 22  discount                      9017 non-null   int64
 23  complaint                     9017 non-null   int64
 24  Feedback                      9017 non-null   int64
dtypes: float64(5), int64(11), object(9)
memory usage: 1.7+ MB

In [19]:
train=train.drop(['customer_id','Name','security_no','referral_id','avg_frequency_login_days','offer_application_preference','complaint_status'],axis=1)

In [20]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9017 entries, 0 to 9016
Data columns (total 18 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   age                    9017 non-null   int64
 1   joining_date           9017 non-null   object
 2   last_visit_time        9017 non-null   object
 3   days_since_last_login  9017 non-null   float64
 4   avg_time_spent         9017 non-null   float64
 5   avg_transaction_value  9017 non-null   float64
 6   points_in_wallet       9017 non-null   float64
 7   churn_risk_score       9017 non-null   float64
 8   Gender                 9017 non-null   int64
 9   Region                 9017 non-null   int64
 10  Membership             9017 non-null   int64
 11  preference             9017 non-null   int64
 12  reference              9017 non-null   int64
 13  medium                 9017 non-null   int64
 14  internet               9017 non-null   int64
 15  discount               9017 non-null   int64
 16  complaint              9017 non-null   int64
 17  Feedback               9017 non-null   int64
dtypes: float64(5), int64(11), object(2)
memory usage: 1.2+ MB

In [21]:
train['joining_date'] = pd.to_datetime(train['joining_date'])

<ipython-input-21-32bebe2e42b3>:1: UserWarning: Parsing dates in DD/MM/YYYY format when dayfirst=False (the default) was specified. This may lead to inconsistently parsed dates! Specify a format to ensure consistent parsing.
  train['joining_date'] = pd.to_datetime(train['joining_date'])

In [22]:
train['year']=train['joining_date'].dt.year
train['month']=train['joining_date'].dt.month
train['day']=train['joining_date'].dt.day

In [23]:
train=train.drop(['joining_date'],axis=1)

In [24]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9017 entries, 0 to 9016
Data columns (total 20 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   age                    9017 non-null   int64
 1   last_visit_time        9017 non-null   object
 2   days_since_last_login  9017 non-null   float64
 3   avg_time_spent         9017 non-null   float64
 4   avg_transaction_value  9017 non-null   float64
 5   points_in_wallet       9017 non-null   float64
 6   churn_risk_score       9017 non-null   float64
 7   Gender                 9017 non-null   int64
 8   Region                 9017 non-null   int64
 9   Membership             9017 non-null   int64
 10  preference             9017 non-null   int64
 11  reference              9017 non-null   int64
 12  medium                 9017 non-null   int64
 13  internet               9017 non-null   int64
 14  discount               9017 non-null   int64
 15  complaint              9017 non-null   int64
 16  Feedback               9017 non-null   int64
 17  year                   9017 non-null   int64
 18  month                  9017 non-null   int64
 19  day                    9017 non-null   int64
dtypes: float64(5), int64(14), object(1)
memory usage: 1.4+ MB

In [25]:
train['last_visit_time'] = pd.to_datetime(train['last_visit_time'])

In [26]:
train['hour']=train['last_visit_time'].dt.hour
train['min']=train['last_visit_time'].dt.minute
train['sec']=train['last_visit_time'].dt.second

In [27]:
train=train.drop(['last_visit_time'],axis=1)

In [28]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9017 entries, 0 to 9016
Data columns (total 22 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   age                    9017 non-null   int64
 1   days_since_last_login  9017 non-null   float64
 2   avg_time_spent         9017 non-null   float64
 3   avg_transaction_value  9017 non-null   float64
 4   points_in_wallet       9017 non-null   float64
 5   churn_risk_score       9017 non-null   float64
 6   Gender                 9017 non-null   int64
 7   Region                 9017 non-null   int64
 8   Membership             9017 non-null   int64
 9   preference             9017 non-null   int64
 10  reference              9017 non-null   int64
 11  medium                 9017 non-null   int64
 12  internet               9017 non-null   int64
 13  discount               9017 non-null   int64
 14  complaint              9017 non-null   int64
 15  Feedback               9017 non-null   int64
 16  year                   9017 non-null   int64
 17  month                  9017 non-null   int64
 18  day                    9017 non-null   int64
 19  hour                   9017 non-null   int64
 20  min                    9017 non-null   int64
 21  sec                    9017 non-null   int64
dtypes: float64(5), int64(17)
memory usage: 1.5 MB

In [29]:
test=pd.read_csv("/test.csv")

In [30]:
test.head()

,customer_id,Name,age,gender,security_no,region_category,membership_category,joining_date,joined_through_referral,referral_id,...,days_since_last_login,avg_time_spent,avg_transaction_value,avg_frequency_login_days,points_in_wallet,used_special_discount,offer_application_preference,past_complaint,complaint_status,feedback
0,fffe43004900440031003700300030003400,Alethia Meints,50,F,OQJ1XAY,Village,Premium Membership,02-11-2015,No,xxxxxxxx,...,12.0,386.26,40721.44,7,733.830000,Yes,No,No,Not Applicable,Poor Product Quality
1,fffe43004900440031003900370037003300,Ming Lopez,41,M,OUQRPKO,Village,Gold Membership,01-03-2016,No,xxxxxxxx,...,11.0,37.80,9644.40,9,726.000000,Yes,No,No,Not Applicable,Poor Website
2,fffe43004900440034003800360037003000,Carina Flannigan,31,F,02J2RE7,Town,Silver Membership,03-03-2017,No,xxxxxxxx,...,18.0,215.36,3693.25,21,713.780000,Yes,No,Yes,Solved in Follow-up,No reason specified
3,fffe43004900440036003200370033003400,Kyung Wanner,64,M,5YEQIF1,Town,Silver Membership,18-08-2017,Yes,CID8941,...,-999.0,44.57,36809.56,11,744.970000,Yes,No,Yes,No Information Available,Too many ads
4,fffe43004900440035003000370031003900,Enola Gatto,16,F,100RYB5,Town,No Membership,05-05-2015,Yes,CID5690,...,6.0,349.88,40675.86,8,299.048351,No,Yes,Yes,Solved in Follow-up,Poor Website

In [31]:
test.shape

(13638, 24)

In [32]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13638 entries, 0 to 13637
Data columns (total 24 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   customer_id                   13638 non-null  object
 1   Name                          13638 non-null  object
 2   age                           13638 non-null  int64
 3   gender                        13638 non-null  object
 4   security_no                   13638 non-null  object
 5   region_category               11607 non-null  object
 6   membership_category           13638 non-null  object
 7   joining_date                  13638 non-null  object
 8   joined_through_referral       13638 non-null  object
 9   referral_id                   13638 non-null  object
 10  preferred_offer_types         13532 non-null  object
 11  medium_of_operation           13638 non-null  object
 12  internet_option               13637 non-null  object
 13  last_visit_time               13637 non-null  object
 14  days_since_last_login         13637 non-null  float64
 15  avg_time_spent                13637 non-null  float64
 16  avg_transaction_value         13637 non-null  float64
 17  avg_frequency_login_days      13637 non-null  object
 18  points_in_wallet              12297 non-null  float64
 19  used_special_discount         13637 non-null  object
 20  offer_application_preference  13637 non-null  object
 21  past_complaint                13637 non-null  object
 22  complaint_status              13637 non-null  object
 23  feedback                      13637 non-null  object
dtypes: float64(4), int64(1), object(19)
memory usage: 2.5+ MB

In [33]:
test.isnull().sum()

customer_id                        0
Name                               0
age                                0
gender                             0
security_no                        0
region_category                 2031
membership_category                0
joining_date                       0
joined_through_referral            0
referral_id                        0
preferred_offer_types            106
medium_of_operation                0
internet_option                    1
last_visit_time                    1
days_since_last_login              1
avg_time_spent                     1
avg_transaction_value              1
avg_frequency_login_days           1
points_in_wallet                1341
used_special_discount              1
offer_application_preference       1
past_complaint                     1
complaint_status                   1
feedback                           1
dtype: int64

In [34]:
test["region_category"]=test["region_category"].fillna(test["region_category"].mode()[0])

In [35]:
test["preferred_offer_types"]=test["preferred_offer_types"].fillna(test["preferred_offer_types"].mode()[0])

In [36]:
test["points_in_wallet"]=test["points_in_wallet"].fillna(test["points_in_wallet"].mean())

In [37]:
test.isnull().sum()

customer_id                     0
Name                            0
age                             0
gender                          0
security_no                     0
region_category                 0
membership_category             0
joining_date                    0
joined_through_referral         0
referral_id                     0
preferred_offer_types           0
medium_of_operation             0
internet_option                 1
last_visit_time                 1
days_since_last_login           1
avg_time_spent                  1
avg_transaction_value           1
avg_frequency_login_days        1
points_in_wallet                0
used_special_discount           1
offer_application_preference    1
past_complaint                  1
complaint_status                1
feedback                        1
dtype: int64

In [38]:
test

,customer_id,Name,age,gender,security_no,region_category,membership_category,joining_date,joined_through_referral,referral_id,...,days_since_last_login,avg_time_spent,avg_transaction_value,avg_frequency_login_days,points_in_wallet,used_special_discount,offer_application_preference,past_complaint,complaint_status,feedback
0,fffe43004900440031003700300030003400,Alethia Meints,50,F,OQJ1XAY,Village,Premium Membership,02-11-2015,No,xxxxxxxx,...,12.0,386.260000,40721.44,7,733.830000,Yes,No,No,Not Applicable,Poor Product Quality
1,fffe43004900440031003900370037003300,Ming Lopez,41,M,OUQRPKO,Village,Gold Membership,01-03-2016,No,xxxxxxxx,...,11.0,37.800000,9644.40,9,726.000000,Yes,No,No,Not Applicable,Poor Website
2,fffe43004900440034003800360037003000,Carina Flannigan,31,F,02J2RE7,Town,Silver Membership,03-03-2017,No,xxxxxxxx,...,18.0,215.360000,3693.25,21,713.780000,Yes,No,Yes,Solved in Follow-up,No reason specified
3,fffe43004900440036003200370033003400,Kyung Wanner,64,M,5YEQIF1,Town,Silver Membership,18-08-2017,Yes,CID8941,...,-999.0,44.570000,36809.56,11,744.970000,Yes,No,Yes,No Information Available,Too many ads
4,fffe43004900440035003000370031003900,Enola Gatto,16,F,100RYB5,Town,No Membership,05-05-2015,Yes,CID5690,...,6.0,349.880000,40675.86,8,299.048351,No,Yes,Yes,Solved in Follow-up,Poor Website
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13633,fffe43004900440035003200330034003200,Dean Redd,58,F,BD4MABX,Town,Platinum Membership,08-04-2016,?,CID14412,...,19.0,30.290000,997.75,Error,767.950000,Yes,No,No,Not Applicable,Too many ads
13634,fffe43004900440036003100360038003300,Kelsie Hice,49,M,CANE3AZ,City,Premium Membership,12-01-2015,Yes,CID59480,...,14.0,1133.243271,11585.43,7,686.230449,Yes,No,No,Not Applicable,Too many ads
13635,fffe43004900440035003100380032003800,Scottie Haddox,61,M,LCW0WC1,City,Platinum Membership,16-07-2015,No,xxxxxxxx,...,20.0,30.070000,46973.76,10,774.960000,Yes,No,Yes,Solved in Follow-up,Poor Website
13636,fffe43004900440031003700350038003100,Shawanda Godbout,12,M,TI2Q466,City,Gold Membership,29-01-2016,Yes,CID28287,...,10.0,153.540000,36494.24,24,634.720000,No,Yes,Yes,Solved,Poor Website
13637,fffe43004900440034003900340036003700,Priscilla Irick,22,F,47SRHQR,Town,Gold Membership,16-02-2016,Yes,xxxxxxxx,...,NaN,NaN,NaN,NaN,686.230449,NaN,NaN,NaN,NaN,NaN

In [42]:
test=test.drop([13637],axis=0)

In [43]:
test["Gender"]=LabelEncoder().fit_transform(test['gender'])
test["Region"]=LabelEncoder().fit_transform(test['region_category'])
test["Membership"]=LabelEncoder().fit_transform(test['membership_category'])
test["preference"]=LabelEncoder().fit_transform(test["preferred_offer_types"])
test["reference"]=LabelEncoder().fit_transform(test["joined_through_referral"])
test["medium"]=LabelEncoder().fit_transform(test["medium_of_operation"])
test["internet"]=LabelEncoder().fit_transform(test["internet_option"])
test["discount"]=LabelEncoder().fit_transform(test["used_special_discount"])
test["complaint"]=LabelEncoder().fit_transform(test["past_complaint"])
test["Feedback"]=LabelEncoder().fit_transform(test["feedback"])

In [44]:
test=test.drop(['customer_id','Name','security_no','referral_id','avg_frequency_login_days','offer_application_preference','complaint_status','gender'],axis=1)

In [45]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13637 entries, 0 to 13636
Data columns (total 26 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   age                      13637 non-null  int64
 1   region_category          13637 non-null  object
 2   membership_category      13637 non-null  object
 3   joining_date             13637 non-null  object
 4   joined_through_referral  13637 non-null  object
 5   preferred_offer_types    13637 non-null  object
 6   medium_of_operation      13637 non-null  object
 7   internet_option          13637 non-null  object
 8   last_visit_time          13637 non-null  object
 9   days_since_last_login    13637 non-null  float64
 10  avg_time_spent           13637 non-null  float64
 11  avg_transaction_value    13637 non-null  float64
 12  points_in_wallet         13637 non-null  float64
 13  used_special_discount    13637 non-null  object
 14  past_complaint           13637 non-null  object
 15  feedback                 13637 non-null  object
 16  Gender                   13637 non-null  int64
 17  Region                   13637 non-null  int64
 18  Membership               13637 non-null  int64
 19  preference               13637 non-null  int64
 20  reference                13637 non-null  int64
 21  medium                   13637 non-null  int64
 22  internet                 13637 non-null  int64
 23  discount                 13637 non-null  int64
 24  complaint                13637 non-null  int64
 25  Feedback                 13637 non-null  int64
dtypes: float64(4), int64(11), object(11)
memory usage: 2.7+ MB

In [47]:
test=test.drop(['region_category','membership_category',"preferred_offer_types","joined_through_referral","medium_of_operation","internet_option","used_special_discount","past_complaint","feedback"],axis=1)

In [48]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13637 entries, 0 to 13636
Data columns (total 17 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   age                    13637 non-null  int64
 1   joining_date           13637 non-null  object
 2   last_visit_time        13637 non-null  object
 3   days_since_last_login  13637 non-null  float64
 4   avg_time_spent         13637 non-null  float64
 5   avg_transaction_value  13637 non-null  float64
 6   points_in_wallet       13637 non-null  float64
 7   Gender                 13637 non-null  int64
 8   Region                 13637 non-null  int64
 9   Membership             13637 non-null  int64
 10  preference             13637 non-null  int64
 11  reference              13637 non-null  int64
 12  medium                 13637 non-null  int64
 13  internet               13637 non-null  int64
 14  discount               13637 non-null  int64
 15  complaint              13637 non-null  int64
 16  Feedback               13637 non-null  int64
dtypes: float64(4), int64(11), object(2)
memory usage: 1.8+ MB

In [49]:
test['joining_date'] = pd.to_datetime(test['joining_date'])

<ipython-input-49-5a78780a00f8>:1: UserWarning: Parsing dates in DD/MM/YYYY format when dayfirst=False (the default) was specified. This may lead to inconsistently parsed dates! Specify a format to ensure consistent parsing.
  test['joining_date'] = pd.to_datetime(test['joining_date'])

In [50]:
test['year']=test['joining_date'].dt.year
test['month']=test['joining_date'].dt.month
test['day']=test['joining_date'].dt.day

In [51]:
test=test.drop(['joining_date'],axis=1)

In [52]:
test['last_visit_time'] = pd.to_datetime(test['last_visit_time'])

In [53]:
test['hour']=test['last_visit_time'].dt.hour
test['min']=test['last_visit_time'].dt.minute
test['sec']=test['last_visit_time'].dt.second

In [54]:
test=test.drop(['last_visit_time'],axis=1)

In [55]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13637 entries, 0 to 13636
Data columns (total 21 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   age                    13637 non-null  int64
 1   days_since_last_login  13637 non-null  float64
 2   avg_time_spent         13637 non-null  float64
 3   avg_transaction_value  13637 non-null  float64
 4   points_in_wallet       13637 non-null  float64
 5   Gender                 13637 non-null  int64
 6   Region                 13637 non-null  int64
 7   Membership             13637 non-null  int64
 8   preference             13637 non-null  int64
 9   reference              13637 non-null  int64
 10  medium                 13637 non-null  int64
 11  internet               13637 non-null  int64
 12  discount               13637 non-null  int64
 13  complaint              13637 non-null  int64
 14  Feedback               13637 non-null  int64
 15  year                   13637 non-null  int64
 16  month                  13637 non-null  int64
 17  day                    13637 non-null  int64
 18  hour                   13637 non-null  int64
 19  min                    13637 non-null  int64
 20  sec                    13637 non-null  int64
dtypes: float64(4), int64(17)
memory usage: 2.2 MB